// Code generated by _scripts/generate-encoder.ts. DO NOT EDIT.

package encoder

import (
	"fmt"

	"github.com/microsoft/typescript-go/internal/ast"
)

func getNodeDataType(node *ast.Node) uint32 {
	switch node.Kind {
	case ast.KindIdentifier,
		ast.KindPrivateIdentifier,
		ast.KindJsxText,
		ast.KindJSDocText,
		ast.KindJSDocLink,
		ast.KindJSDocLinkPlain,
		ast.KindJSDocLinkCode:
		return NodeDataTypeString
	case ast.KindStringLiteral,
		ast.KindNumericLiteral,
		ast.KindBigIntLiteral,
		ast.KindRegularExpressionLiteral,
		ast.KindNoSubstitutionTemplateLiteral,
		ast.KindTemplateHead,
		ast.KindTemplateMiddle,
		ast.KindTemplateTail,
		ast.KindSourceFile:
		return NodeDataTypeExtendedData
	default:
		return NodeDataTypeChildren
	}
}

func getChildrenPropertyMask(node *ast.Node) uint16 {
	switch node.Kind {
	case ast.KindQualifiedName:
		n := node.AsQualifiedName()
		return (boolToUint16(n.Left != nil) << 0) | (boolToUint16(n.Right != nil) << 1)
	case ast.KindComputedPropertyName:
		n := node.AsComputedPropertyName()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindDecorator:
		n := node.AsDecorator()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindIfStatement:
		n := node.AsIfStatement()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.ThenStatement != nil) << 1) | (boolToUint16(n.ElseStatement != nil) << 2)
	case ast.KindDoStatement:
		n := node.AsDoStatement()
		return (boolToUint16(n.Statement != nil) << 0) | (boolToUint16(n.Expression != nil) << 1)
	case ast.KindWhileStatement:
		n := node.AsWhileStatement()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.Statement != nil) << 1)
	case ast.KindForStatement:
		n := node.AsForStatement()
		return (boolToUint16(n.Initializer != nil) << 0) | (boolToUint16(n.Condition != nil) << 1) | (boolToUint16(n.Incrementor != nil) << 2) | (boolToUint16(n.Statement != nil) << 3)
	case ast.KindForInStatement, ast.KindForOfStatement:
		n := node.AsForInOrOfStatement()
		return (boolToUint16(n.AwaitModifier != nil) << 0) | (boolToUint16(n.Initializer != nil) << 1) | (boolToUint16(n.Expression != nil) << 2) | (boolToUint16(n.Statement != nil) << 3)
	case ast.KindBreakStatement:
		n := node.AsBreakStatement()
		return (boolToUint16(n.Label != nil) << 0)
	case ast.KindContinueStatement:
		n := node.AsContinueStatement()
		return (boolToUint16(n.Label != nil) << 0)
	case ast.KindReturnStatement:
		n := node.AsReturnStatement()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindWithStatement:
		n := node.AsWithStatement()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.Statement != nil) << 1)
	case ast.KindSwitchStatement:
		n := node.AsSwitchStatement()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.CaseBlock != nil) << 1)
	case ast.KindCaseBlock:
		n := node.AsCaseBlock()
		return (boolToUint16(n.Clauses != nil) << 0)
	case ast.KindCaseClause, ast.KindDefaultClause:
		n := node.AsCaseOrDefaultClause()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.Statements != nil) << 1)
	case ast.KindThrowStatement:
		n := node.AsThrowStatement()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindTryStatement:
		n := node.AsTryStatement()
		return (boolToUint16(n.TryBlock != nil) << 0) | (boolToUint16(n.CatchClause != nil) << 1) | (boolToUint16(n.FinallyBlock != nil) << 2)
	case ast.KindCatchClause:
		n := node.AsCatchClause()
		return (boolToUint16(n.VariableDeclaration != nil) << 0) | (boolToUint16(n.Block != nil) << 1)
	case ast.KindLabeledStatement:
		n := node.AsLabeledStatement()
		return (boolToUint16(n.Label != nil) << 0) | (boolToUint16(n.Statement != nil) << 1)
	case ast.KindExpressionStatement:
		n := node.AsExpressionStatement()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindBlock:
		n := node.AsBlock()
		return (boolToUint16(n.Statements != nil) << 0)
	case ast.KindVariableStatement:
		n := node.AsVariableStatement()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.DeclarationList != nil) << 1)
	case ast.KindVariableDeclaration:
		n := node.AsVariableDeclaration()
		return (boolToUint16(n.Name() != nil) << 0) | (boolToUint16(n.ExclamationToken != nil) << 1) | (boolToUint16(n.Type != nil) << 2) | (boolToUint16(n.Initializer != nil) << 3)
	case ast.KindVariableDeclarationList:
		n := node.AsVariableDeclarationList()
		return (boolToUint16(n.Declarations != nil) << 0)
	case ast.KindObjectBindingPattern, ast.KindArrayBindingPattern:
		n := node.AsBindingPattern()
		return (boolToUint16(n.Elements != nil) << 0)
	case ast.KindParameter:
		n := node.AsParameterDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.DotDotDotToken != nil) << 1) | (boolToUint16(n.Name() != nil) << 2) | (boolToUint16(n.QuestionToken != nil) << 3) | (boolToUint16(n.Type != nil) << 4) | (boolToUint16(n.Initializer != nil) << 5)
	case ast.KindBindingElement:
		n := node.AsBindingElement()
		return (boolToUint16(n.DotDotDotToken != nil) << 0) | (boolToUint16(n.PropertyName != nil) << 1) | (boolToUint16(n.Name() != nil) << 2) | (boolToUint16(n.Initializer != nil) << 3)
	case ast.KindMissingDeclaration:
		n := node.AsMissingDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0)
	case ast.KindFunctionDeclaration:
		n := node.AsFunctionDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.AsteriskToken != nil) << 1) | (boolToUint16(n.Name() != nil) << 2) | (boolToUint16(n.TypeParameters != nil) << 3) | (boolToUint16(n.Parameters != nil) << 4) | (boolToUint16(n.Type != nil) << 5) | (boolToUint16(n.ThrowsType != nil) << 6) | (boolToUint16(n.Body != nil) << 7)
	case ast.KindClassDeclaration:
		n := node.AsClassDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.TypeParameters != nil) << 2) | (boolToUint16(n.HeritageClauses != nil) << 3) | (boolToUint16(n.Members != nil) << 4)
	case ast.KindClassExpression:
		n := node.AsClassExpression()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.TypeParameters != nil) << 2) | (boolToUint16(n.HeritageClauses != nil) << 3) | (boolToUint16(n.Members != nil) << 4)
	case ast.KindHeritageClause:
		n := node.AsHeritageClause()
		return (boolToUint16(n.Types != nil) << 0)
	case ast.KindInterfaceDeclaration:
		n := node.AsInterfaceDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.TypeParameters != nil) << 2) | (boolToUint16(n.HeritageClauses != nil) << 3) | (boolToUint16(n.Members != nil) << 4)
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		n := node.AsTypeAliasDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.TypeParameters != nil) << 2) | (boolToUint16(n.Type != nil) << 3)
	case ast.KindEnumMember:
		n := node.AsEnumMember()
		return (boolToUint16(n.Name() != nil) << 0) | (boolToUint16(n.Initializer != nil) << 1)
	case ast.KindEnumDeclaration:
		n := node.AsEnumDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.Members != nil) << 2)
	case ast.KindModuleBlock:
		n := node.AsModuleBlock()
		return (boolToUint16(n.Statements != nil) << 0)
	case ast.KindImportDeclaration, ast.KindJSImportDeclaration:
		n := node.AsImportDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.ImportClause != nil) << 1) | (boolToUint16(n.ModuleSpecifier != nil) << 2) | (boolToUint16(n.Attributes != nil) << 3)
	case ast.KindExternalModuleReference:
		n := node.AsExternalModuleReference()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindNamespaceImport:
		n := node.AsNamespaceImport()
		return (boolToUint16(n.Name() != nil) << 0)
	case ast.KindNamedImports:
		n := node.AsNamedImports()
		return (boolToUint16(n.Elements != nil) << 0)
	case ast.KindExportAssignment:
		n := node.AsExportAssignment()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Type != nil) << 1) | (boolToUint16(n.Expression != nil) << 2)
	case ast.KindNamespaceExportDeclaration:
		n := node.AsNamespaceExportDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1)
	case ast.KindNamespaceExport:
		n := node.AsNamespaceExport()
		return (boolToUint16(n.Name() != nil) << 0)
	case ast.KindNamedExports:
		n := node.AsNamedExports()
		return (boolToUint16(n.Elements != nil) << 0)
	case ast.KindExportSpecifier:
		n := node.AsExportSpecifier()
		return (boolToUint16(n.PropertyName != nil) << 0) | (boolToUint16(n.Name() != nil) << 1)
	case ast.KindCallSignature:
		n := node.AsCallSignatureDeclaration()
		return (boolToUint16(n.TypeParameters != nil) << 0) | (boolToUint16(n.Parameters != nil) << 1) | (boolToUint16(n.Type != nil) << 2) | (boolToUint16(n.ThrowsType != nil) << 3)
	case ast.KindConstructSignature:
		n := node.AsConstructSignatureDeclaration()
		return (boolToUint16(n.TypeParameters != nil) << 0) | (boolToUint16(n.Parameters != nil) << 1) | (boolToUint16(n.Type != nil) << 2) | (boolToUint16(n.ThrowsType != nil) << 3)
	case ast.KindConstructor:
		n := node.AsConstructorDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.TypeParameters != nil) << 1) | (boolToUint16(n.Parameters != nil) << 2) | (boolToUint16(n.Type != nil) << 3) | (boolToUint16(n.ThrowsType != nil) << 4) | (boolToUint16(n.Body != nil) << 5)
	case ast.KindGetAccessor:
		n := node.AsGetAccessorDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.TypeParameters != nil) << 2) | (boolToUint16(n.Parameters != nil) << 3) | (boolToUint16(n.Type != nil) << 4) | (boolToUint16(n.ThrowsType != nil) << 5) | (boolToUint16(n.Body != nil) << 6)
	case ast.KindSetAccessor:
		n := node.AsSetAccessorDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.TypeParameters != nil) << 2) | (boolToUint16(n.Parameters != nil) << 3) | (boolToUint16(n.Type != nil) << 4) | (boolToUint16(n.ThrowsType != nil) << 5) | (boolToUint16(n.Body != nil) << 6)
	case ast.KindIndexSignature:
		n := node.AsIndexSignatureDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Parameters != nil) << 1) | (boolToUint16(n.Type != nil) << 2)
	case ast.KindMethodSignature:
		n := node.AsMethodSignatureDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.PostfixToken != nil) << 2) | (boolToUint16(n.TypeParameters != nil) << 3) | (boolToUint16(n.Parameters != nil) << 4) | (boolToUint16(n.Type != nil) << 5) | (boolToUint16(n.ThrowsType != nil) << 6)
	case ast.KindMethodDeclaration:
		n := node.AsMethodDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.AsteriskToken != nil) << 1) | (boolToUint16(n.Name() != nil) << 2) | (boolToUint16(n.PostfixToken != nil) << 3) | (boolToUint16(n.TypeParameters != nil) << 4) | (boolToUint16(n.Parameters != nil) << 5) | (boolToUint16(n.Type != nil) << 6) | (boolToUint16(n.ThrowsType != nil) << 7) | (boolToUint16(n.Body != nil) << 8)
	case ast.KindPropertySignature:
		n := node.AsPropertySignatureDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.PostfixToken != nil) << 2) | (boolToUint16(n.Type != nil) << 3) | (boolToUint16(n.Initializer != nil) << 4)
	case ast.KindPropertyDeclaration:
		n := node.AsPropertyDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.PostfixToken != nil) << 2) | (boolToUint16(n.Type != nil) << 3) | (boolToUint16(n.Initializer != nil) << 4)
	case ast.KindClassStaticBlockDeclaration:
		n := node.AsClassStaticBlockDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Body != nil) << 1)
	case ast.KindBinaryExpression:
		n := node.AsBinaryExpression()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Left != nil) << 1) | (boolToUint16(n.Type != nil) << 2) | (boolToUint16(n.OperatorToken != nil) << 3) | (boolToUint16(n.Right != nil) << 4)
	case ast.KindPrefixUnaryExpression:
		n := node.AsPrefixUnaryExpression()
		return (boolToUint16(n.Operand != nil) << 0)
	case ast.KindPostfixUnaryExpression:
		n := node.AsPostfixUnaryExpression()
		return (boolToUint16(n.Operand != nil) << 0)
	case ast.KindYieldExpression:
		n := node.AsYieldExpression()
		return (boolToUint16(n.AsteriskToken != nil) << 0) | (boolToUint16(n.Expression != nil) << 1)
	case ast.KindArrowFunction:
		n := node.AsArrowFunction()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.TypeParameters != nil) << 1) | (boolToUint16(n.Parameters != nil) << 2) | (boolToUint16(n.Type != nil) << 3) | (boolToUint16(n.ThrowsType != nil) << 4) | (boolToUint16(n.EqualsGreaterThanToken != nil) << 5) | (boolToUint16(n.Body != nil) << 6)
	case ast.KindFunctionExpression:
		n := node.AsFunctionExpression()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.AsteriskToken != nil) << 1) | (boolToUint16(n.Name() != nil) << 2) | (boolToUint16(n.TypeParameters != nil) << 3) | (boolToUint16(n.Parameters != nil) << 4) | (boolToUint16(n.Type != nil) << 5) | (boolToUint16(n.ThrowsType != nil) << 6) | (boolToUint16(n.Body != nil) << 7)
	case ast.KindAsExpression:
		n := node.AsAsExpression()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.Type != nil) << 1)
	case ast.KindSatisfiesExpression:
		n := node.AsSatisfiesExpression()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.Type != nil) << 1)
	case ast.KindConditionalExpression:
		n := node.AsConditionalExpression()
		return (boolToUint16(n.Condition != nil) << 0) | (boolToUint16(n.QuestionToken != nil) << 1) | (boolToUint16(n.WhenTrue != nil) << 2) | (boolToUint16(n.ColonToken != nil) << 3) | (boolToUint16(n.WhenFalse != nil) << 4)
	case ast.KindPropertyAccessExpression:
		n := node.AsPropertyAccessExpression()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.QuestionDotToken != nil) << 1) | (boolToUint16(n.Name() != nil) << 2)
	case ast.KindElementAccessExpression:
		n := node.AsElementAccessExpression()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.QuestionDotToken != nil) << 1) | (boolToUint16(n.ArgumentExpression != nil) << 2)
	case ast.KindCallExpression:
		n := node.AsCallExpression()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.QuestionDotToken != nil) << 1) | (boolToUint16(n.TypeArguments != nil) << 2) | (boolToUint16(n.Arguments != nil) << 3)
	case ast.KindNewExpression:
		n := node.AsNewExpression()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.TypeArguments != nil) << 1) | (boolToUint16(n.Arguments != nil) << 2)
	case ast.KindMetaProperty:
		n := node.AsMetaProperty()
		return (boolToUint16(n.Name() != nil) << 0)
	case ast.KindNonNullExpression:
		n := node.AsNonNullExpression()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindSpreadElement:
		n := node.AsSpreadElement()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindTemplateExpression:
		n := node.AsTemplateExpression()
		return (boolToUint16(n.Head != nil) << 0) | (boolToUint16(n.TemplateSpans != nil) << 1)
	case ast.KindTemplateSpan:
		n := node.AsTemplateSpan()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.Literal != nil) << 1)
	case ast.KindTaggedTemplateExpression:
		n := node.AsTaggedTemplateExpression()
		return (boolToUint16(n.Tag != nil) << 0) | (boolToUint16(n.QuestionDotToken != nil) << 1) | (boolToUint16(n.TypeArguments != nil) << 2) | (boolToUint16(n.Template != nil) << 3)
	case ast.KindParenthesizedExpression:
		n := node.AsParenthesizedExpression()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindArrayLiteralExpression:
		n := node.AsArrayLiteralExpression()
		return (boolToUint16(n.Elements != nil) << 0)
	case ast.KindObjectLiteralExpression:
		n := node.AsObjectLiteralExpression()
		return (boolToUint16(n.Properties != nil) << 0)
	case ast.KindSpreadAssignment:
		n := node.AsSpreadAssignment()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindPropertyAssignment:
		n := node.AsPropertyAssignment()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.PostfixToken != nil) << 2) | (boolToUint16(n.Type != nil) << 3) | (boolToUint16(n.Initializer != nil) << 4)
	case ast.KindShorthandPropertyAssignment:
		n := node.AsShorthandPropertyAssignment()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.PostfixToken != nil) << 2) | (boolToUint16(n.Type != nil) << 3) | (boolToUint16(n.EqualsToken != nil) << 4) | (boolToUint16(n.ObjectAssignmentInitializer != nil) << 5)
	case ast.KindDeleteExpression:
		n := node.AsDeleteExpression()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindTypeOfExpression:
		n := node.AsTypeOfExpression()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindVoidExpression:
		n := node.AsVoidExpression()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindAwaitExpression:
		n := node.AsAwaitExpression()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindTypeAssertionExpression:
		n := node.AsTypeAssertion()
		return (boolToUint16(n.Type != nil) << 0) | (boolToUint16(n.Expression != nil) << 1)
	case ast.KindUnionType:
		n := node.AsUnionTypeNode()
		return (boolToUint16(n.Types != nil) << 0)
	case ast.KindIntersectionType:
		n := node.AsIntersectionTypeNode()
		return (boolToUint16(n.Types != nil) << 0)
	case ast.KindConditionalType:
		n := node.AsConditionalTypeNode()
		return (boolToUint16(n.CheckType != nil) << 0) | (boolToUint16(n.ExtendsType != nil) << 1) | (boolToUint16(n.TrueType != nil) << 2) | (boolToUint16(n.FalseType != nil) << 3)
	case ast.KindTypeOperator:
		n := node.AsTypeOperatorNode()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindInferType:
		n := node.AsInferTypeNode()
		return (boolToUint16(n.TypeParameter != nil) << 0)
	case ast.KindArrayType:
		n := node.AsArrayTypeNode()
		return (boolToUint16(n.ElementType != nil) << 0)
	case ast.KindIndexedAccessType:
		n := node.AsIndexedAccessTypeNode()
		return (boolToUint16(n.ObjectType != nil) << 0) | (boolToUint16(n.IndexType != nil) << 1)
	case ast.KindTypeReference:
		n := node.AsTypeReferenceNode()
		return (boolToUint16(n.TypeName != nil) << 0) | (boolToUint16(n.TypeArguments != nil) << 1)
	case ast.KindExpressionWithTypeArguments:
		n := node.AsExpressionWithTypeArguments()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.TypeArguments != nil) << 1)
	case ast.KindLiteralType:
		n := node.AsLiteralTypeNode()
		return (boolToUint16(n.Literal != nil) << 0)
	case ast.KindTypePredicate:
		n := node.AsTypePredicateNode()
		return (boolToUint16(n.AssertsModifier != nil) << 0) | (boolToUint16(n.ParameterName != nil) << 1) | (boolToUint16(n.Type != nil) << 2)
	case ast.KindImportAttribute:
		n := node.AsImportAttribute()
		return (boolToUint16(n.Name() != nil) << 0) | (boolToUint16(n.Value != nil) << 1)
	case ast.KindImportAttributes:
		n := node.AsImportAttributes()
		return (boolToUint16(n.Attributes != nil) << 0)
	case ast.KindTypeQuery:
		n := node.AsTypeQueryNode()
		return (boolToUint16(n.ExprName != nil) << 0) | (boolToUint16(n.TypeArguments != nil) << 1)
	case ast.KindMappedType:
		n := node.AsMappedTypeNode()
		return (boolToUint16(n.ReadonlyToken != nil) << 0) | (boolToUint16(n.TypeParameter != nil) << 1) | (boolToUint16(n.NameType != nil) << 2) | (boolToUint16(n.QuestionToken != nil) << 3) | (boolToUint16(n.Type != nil) << 4) | (boolToUint16(n.Members != nil) << 5)
	case ast.KindTypeLiteral:
		n := node.AsTypeLiteralNode()
		return (boolToUint16(n.Members != nil) << 0)
	case ast.KindTupleType:
		n := node.AsTupleTypeNode()
		return (boolToUint16(n.Elements != nil) << 0)
	case ast.KindNamedTupleMember:
		n := node.AsNamedTupleMember()
		return (boolToUint16(n.DotDotDotToken != nil) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.QuestionToken != nil) << 2) | (boolToUint16(n.Type != nil) << 3)
	case ast.KindOptionalType:
		n := node.AsOptionalTypeNode()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindRestType:
		n := node.AsRestTypeNode()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindParenthesizedType:
		n := node.AsParenthesizedTypeNode()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindFunctionType:
		n := node.AsFunctionTypeNode()
		return (boolToUint16(n.TypeParameters != nil) << 0) | (boolToUint16(n.Parameters != nil) << 1) | (boolToUint16(n.Type != nil) << 2) | (boolToUint16(n.ThrowsType != nil) << 3)
	case ast.KindConstructorType:
		n := node.AsConstructorTypeNode()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.TypeParameters != nil) << 1) | (boolToUint16(n.Parameters != nil) << 2) | (boolToUint16(n.Type != nil) << 3) | (boolToUint16(n.ThrowsType != nil) << 4)
	case ast.KindTemplateLiteralType:
		n := node.AsTemplateLiteralTypeNode()
		return (boolToUint16(n.Head != nil) << 0) | (boolToUint16(n.TemplateSpans != nil) << 1)
	case ast.KindTemplateLiteralTypeSpan:
		n := node.AsTemplateLiteralTypeSpan()
		return (boolToUint16(n.Type != nil) << 0) | (boolToUint16(n.Literal != nil) << 1)
	case ast.KindSyntheticExpression:
		n := node.AsSyntheticExpression()
		return (boolToUint16(n.TupleNameSource != nil) << 0)
	case ast.KindPartiallyEmittedExpression:
		n := node.AsPartiallyEmittedExpression()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindJsxElement:
		n := node.AsJsxElement()
		return (boolToUint16(n.OpeningElement != nil) << 0) | (boolToUint16(n.Children != nil) << 1) | (boolToUint16(n.ClosingElement != nil) << 2)
	case ast.KindJsxAttributes:
		n := node.AsJsxAttributes()
		return (boolToUint16(n.Properties != nil) << 0)
	case ast.KindJsxNamespacedName:
		n := node.AsJsxNamespacedName()
		return (boolToUint16(n.Namespace != nil) << 0) | (boolToUint16(n.Name() != nil) << 1)
	case ast.KindJsxOpeningElement:
		n := node.AsJsxOpeningElement()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeArguments != nil) << 1) | (boolToUint16(n.Attributes != nil) << 2)
	case ast.KindJsxSelfClosingElement:
		n := node.AsJsxSelfClosingElement()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeArguments != nil) << 1) | (boolToUint16(n.Attributes != nil) << 2)
	case ast.KindJsxFragment:
		n := node.AsJsxFragment()
		return (boolToUint16(n.OpeningFragment != nil) << 0) | (boolToUint16(n.Children != nil) << 1) | (boolToUint16(n.ClosingFragment != nil) << 2)
	case ast.KindJsxAttribute:
		n := node.AsJsxAttribute()
		return (boolToUint16(n.Name() != nil) << 0) | (boolToUint16(n.Initializer != nil) << 1)
	case ast.KindJsxSpreadAttribute:
		n := node.AsJsxSpreadAttribute()
		return (boolToUint16(n.Expression != nil) << 0)
	case ast.KindJsxClosingElement:
		n := node.AsJsxClosingElement()
		return (boolToUint16(n.TagName != nil) << 0)
	case ast.KindJsxExpression:
		n := node.AsJsxExpression()
		return (boolToUint16(n.DotDotDotToken != nil) << 0) | (boolToUint16(n.Expression != nil) << 1)
	case ast.KindSyntaxList:
		n := node.AsSyntaxList()
		return (boolToUint16(len(n.Children) > 0) << 0)
	case ast.KindJSDoc:
		n := node.AsJSDoc()
		return (boolToUint16(n.Comment != nil) << 0) | (boolToUint16(n.Tags != nil) << 1)
	case ast.KindJSDocTypeExpression:
		n := node.AsJSDocTypeExpression()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindJSDocNonNullableType:
		n := node.AsJSDocNonNullableType()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindJSDocNullableType:
		n := node.AsJSDocNullableType()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindJSDocVariadicType:
		n := node.AsJSDocVariadicType()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindJSDocOptionalType:
		n := node.AsJSDocOptionalType()
		return (boolToUint16(n.Type != nil) << 0)
	case ast.KindJSDocTypeTag:
		n := node.AsJSDocTypeTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeExpression != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocUnknownTag:
		n := node.AsJSDocUnknownTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Comment != nil) << 1)
	case ast.KindJSDocTemplateTag:
		n := node.AsJSDocTemplateTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Constraint != nil) << 1) | (boolToUint16(n.TypeParameters != nil) << 2) | (boolToUint16(n.Comment != nil) << 3)
	case ast.KindJSDocReturnTag:
		n := node.AsJSDocReturnTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeExpression != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocPublicTag:
		n := node.AsJSDocPublicTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Comment != nil) << 1)
	case ast.KindJSDocPrivateTag:
		n := node.AsJSDocPrivateTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Comment != nil) << 1)
	case ast.KindJSDocProtectedTag:
		n := node.AsJSDocProtectedTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Comment != nil) << 1)
	case ast.KindJSDocReadonlyTag:
		n := node.AsJSDocReadonlyTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Comment != nil) << 1)
	case ast.KindJSDocOverrideTag:
		n := node.AsJSDocOverrideTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Comment != nil) << 1)
	case ast.KindJSDocDeprecatedTag:
		n := node.AsJSDocDeprecatedTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Comment != nil) << 1)
	case ast.KindJSDocSeeTag:
		n := node.AsJSDocSeeTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.NameExpression != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocImplementsTag:
		n := node.AsJSDocImplementsTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.ClassName != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocAugmentsTag:
		n := node.AsJSDocAugmentsTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.ClassName != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocSatisfiesTag:
		n := node.AsJSDocSatisfiesTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeExpression != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocThrowsTag:
		n := node.AsJSDocThrowsTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeExpression != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocThisTag:
		n := node.AsJSDocThisTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeExpression != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocImportTag:
		n := node.AsJSDocImportTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.ImportClause != nil) << 1) | (boolToUint16(n.ModuleSpecifier != nil) << 2) | (boolToUint16(n.Attributes != nil) << 3) | (boolToUint16(n.Comment != nil) << 4)
	case ast.KindJSDocCallbackTag:
		n := node.AsJSDocCallbackTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeExpression != nil) << 1) | (boolToUint16(n.Name() != nil) << 2) | (boolToUint16(n.Comment != nil) << 3)
	case ast.KindJSDocOverloadTag:
		n := node.AsJSDocOverloadTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeExpression != nil) << 1) | (boolToUint16(n.Comment != nil) << 2)
	case ast.KindJSDocTypedefTag:
		n := node.AsJSDocTypedefTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.TypeExpression != nil) << 1) | (boolToUint16(n.Name() != nil) << 2) | (boolToUint16(n.Comment != nil) << 3)
	case ast.KindJSDocSignature:
		n := node.AsJSDocSignature()
		return (boolToUint16(n.TypeParameters != nil) << 0) | (boolToUint16(n.Parameters != nil) << 1) | (boolToUint16(n.Type != nil) << 2)
	case ast.KindJSDocNameReference:
		n := node.AsJSDocNameReference()
		return (boolToUint16(n.Name() != nil) << 0)
	case ast.KindModuleDeclaration:
		n := node.AsModuleDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.Body != nil) << 2)
	case ast.KindImportEqualsDeclaration:
		n := node.AsImportEqualsDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.ModuleReference != nil) << 2)
	case ast.KindExportDeclaration:
		n := node.AsExportDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.ExportClause != nil) << 1) | (boolToUint16(n.ModuleSpecifier != nil) << 2) | (boolToUint16(n.Attributes != nil) << 3)
	case ast.KindImportType:
		n := node.AsImportTypeNode()
		return (boolToUint16(n.Argument != nil) << 0) | (boolToUint16(n.Attributes != nil) << 1) | (boolToUint16(n.Qualifier != nil) << 2) | (boolToUint16(n.TypeArguments != nil) << 3)
	case ast.KindImportClause:
		n := node.AsImportClause()
		return (boolToUint16(n.Name() != nil) << 0) | (boolToUint16(n.NamedBindings != nil) << 1)
	case ast.KindImportSpecifier:
		n := node.AsImportSpecifier()
		return (boolToUint16(n.PropertyName != nil) << 0) | (boolToUint16(n.Name() != nil) << 1)
	case ast.KindJSDocLink:
		n := node.AsJSDocLink()
		return (boolToUint16(n.Name() != nil) << 0)
	case ast.KindJSDocLinkPlain:
		n := node.AsJSDocLinkPlain()
		return (boolToUint16(n.Name() != nil) << 0)
	case ast.KindJSDocLinkCode:
		n := node.AsJSDocLinkCode()
		return (boolToUint16(n.Name() != nil) << 0)
	case ast.KindTypeParameter:
		n := node.AsTypeParameterDeclaration()
		return (boolToUint16(hasModifiers(n.Modifiers())) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.Constraint != nil) << 2) | (boolToUint16(n.Expression != nil) << 3) | (boolToUint16(n.DefaultType != nil) << 4)
	case ast.KindSyntheticReferenceExpression:
		n := node.AsSyntheticReferenceExpression()
		return (boolToUint16(n.Expression != nil) << 0) | (boolToUint16(n.ThisArg != nil) << 1)
	case ast.KindJSDocTypeLiteral:
		n := node.AsJSDocTypeLiteral()
		return (boolToUint16(len(n.JSDocPropertyTags) > 0) << 0)
	case ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:
		n := node.AsJSDocParameterOrPropertyTag()
		return (boolToUint16(n.TagName != nil) << 0) | (boolToUint16(n.Name() != nil) << 1) | (boolToUint16(n.TypeExpression != nil) << 2) | (boolToUint16(n.Comment != nil) << 3)
	default:
		return 0
	}
}

func getNodeCommonData(node *ast.Node) uint32 {
	switch node.Kind {
	case ast.KindBlock:
		n := node.AsBlock()
		return uint32(boolToByte(n.MultiLine)) << 24
	case ast.KindHeritageClause:
		n := node.AsHeritageClause()
		var tokenIdx uint32
		switch n.Token {
		case ast.KindImplementsKeyword:
			tokenIdx = 1
		}
		return tokenIdx << 24
	case ast.KindExportAssignment:
		n := node.AsExportAssignment()
		return uint32(boolToByte(n.IsExportEquals)) << 24
	case ast.KindExportSpecifier:
		n := node.AsExportSpecifier()
		return uint32(boolToByte(n.IsTypeOnly)) << 24
	case ast.KindPrefixUnaryExpression:
		n := node.AsPrefixUnaryExpression()
		var operatorIdx uint32
		switch n.Operator {
		case ast.KindMinusToken:
			operatorIdx = 1
		case ast.KindTildeToken:
			operatorIdx = 2
		case ast.KindExclamationToken:
			operatorIdx = 3
		case ast.KindPlusPlusToken:
			operatorIdx = 4
		case ast.KindMinusMinusToken:
			operatorIdx = 5
		}
		return operatorIdx << 24
	case ast.KindPostfixUnaryExpression:
		n := node.AsPostfixUnaryExpression()
		var operatorIdx uint32
		switch n.Operator {
		case ast.KindMinusMinusToken:
			operatorIdx = 1
		}
		return operatorIdx << 24
	case ast.KindMetaProperty:
		n := node.AsMetaProperty()
		var keywordTokenIdx uint32
		switch n.KeywordToken {
		case ast.KindNewKeyword:
			keywordTokenIdx = 1
		}
		return keywordTokenIdx << 24
	case ast.KindArrayLiteralExpression:
		n := node.AsArrayLiteralExpression()
		return uint32(boolToByte(n.MultiLine)) << 24
	case ast.KindObjectLiteralExpression:
		n := node.AsObjectLiteralExpression()
		return uint32(boolToByte(n.MultiLine)) << 24
	case ast.KindTypeOperator:
		n := node.AsTypeOperatorNode()
		var operatorIdx uint32
		switch n.Operator {
		case ast.KindReadonlyKeyword:
			operatorIdx = 1
		case ast.KindUniqueKeyword:
			operatorIdx = 2
		}
		return operatorIdx << 24
	case ast.KindImportAttributes:
		n := node.AsImportAttributes()
		var tokenIdx uint32
		switch n.Token {
		case ast.KindAssertKeyword:
			tokenIdx = 1
		}
		return uint32(boolToByte(n.MultiLine))<<24 | tokenIdx<<25
	case ast.KindSyntheticExpression:
		return getNodeCommonData_SyntheticExpression(node)
	case ast.KindJsxText:
		n := node.AsJsxText()
		return uint32(boolToByte(n.ContainsOnlyTriviaWhiteSpaces)) << 24
	case ast.KindModuleDeclaration:
		n := node.AsModuleDeclaration()
		var keywordIdx uint32
		switch n.Keyword {
		case ast.KindNamespaceKeyword:
			keywordIdx = 1
		}
		return keywordIdx << 24
	case ast.KindImportEqualsDeclaration:
		n := node.AsImportEqualsDeclaration()
		return uint32(boolToByte(n.IsTypeOnly)) << 24
	case ast.KindExportDeclaration:
		n := node.AsExportDeclaration()
		return uint32(boolToByte(n.IsTypeOnly)) << 24
	case ast.KindImportType:
		n := node.AsImportTypeNode()
		return uint32(boolToByte(n.IsTypeOf)) << 24
	case ast.KindImportClause:
		n := node.AsImportClause()
		var phaseModifierIdx uint32
		switch n.PhaseModifier {
		case ast.KindTypeKeyword:
			phaseModifierIdx = 1
		case ast.KindDeferKeyword:
			phaseModifierIdx = 2
		}
		return phaseModifierIdx << 24
	case ast.KindImportSpecifier:
		n := node.AsImportSpecifier()
		return uint32(boolToByte(n.IsTypeOnly)) << 24
	case ast.KindJSDocTypeLiteral:
		n := node.AsJSDocTypeLiteral()
		return uint32(boolToByte(n.IsArrayType)) << 24
	case ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:
		n := node.AsJSDocParameterOrPropertyTag()
		return uint32(boolToByte(n.IsBracketed))<<24 | uint32(boolToByte(n.IsNameFirst))<<25
	}
	return 0
}

func recordNodeStrings(node *ast.Node, strs *stringTable) uint32 {
	switch node.Kind {
	case ast.KindIdentifier:
		return strs.add(node.AsIdentifier().Text, node.Kind, node.Pos(), node.End())
	case ast.KindPrivateIdentifier:
		return strs.add(node.AsPrivateIdentifier().Text, node.Kind, node.Pos(), node.End())
	case ast.KindJsxText:
		return strs.add(node.AsJsxText().Text, node.Kind, node.Pos(), node.End())
	case ast.KindJSDocText:
		return strs.add(node.AsJSDocText().Text(), node.Kind, node.Pos(), node.End())
	case ast.KindJSDocLink:
		return strs.add(node.AsJSDocLink().Text(), node.Kind, node.Pos(), node.End())
	case ast.KindJSDocLinkPlain:
		return strs.add(node.AsJSDocLinkPlain().Text(), node.Kind, node.Pos(), node.End())
	case ast.KindJSDocLinkCode:
		return strs.add(node.AsJSDocLinkCode().Text(), node.Kind, node.Pos(), node.End())
	default:
		panic(fmt.Sprintf("Unexpected node kind %v", node.Kind))
	}
}

func recordExtendedData(node *ast.Node, strs *stringTable, positionMap *ast.PositionMap, extendedData *[]byte, structuredData *[]byte) uint32 {
	offset := uint32(len(*extendedData))
	switch node.Kind {
	case ast.KindStringLiteral:
		recordExtendedData_StringLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindNumericLiteral:
		recordExtendedData_NumericLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindBigIntLiteral:
		recordExtendedData_BigIntLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindRegularExpressionLiteral:
		recordExtendedData_RegularExpressionLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindNoSubstitutionTemplateLiteral:
		recordExtendedData_NoSubstitutionTemplateLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindTemplateHead:
		recordExtendedData_TemplateHead(node, strs, positionMap, extendedData, structuredData)
	case ast.KindTemplateMiddle:
		recordExtendedData_TemplateMiddle(node, strs, positionMap, extendedData, structuredData)
	case ast.KindTemplateTail:
		recordExtendedData_TemplateTail(node, strs, positionMap, extendedData, structuredData)
	case ast.KindSourceFile:
		recordExtendedData_SourceFile(node, strs, positionMap, extendedData, structuredData)
	default:
		panic(fmt.Sprintf("unknown extended data node kind %v", node.Kind))
	}
	return offset
}
